#Rename this file to docker-compose.yaml for it to work properly with docker
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev #or Dockerfile to production
    ports:
      - 5000:80
    volumes:
      - .:/app #only dev
    environment:
      - SERVER_MODE=dev #or prod - by default is dev
      - SERVER_PORT=80 #port by default is 5000
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=mytaskboard
    deploy:
      resources:
        limits:
          cpus: 1
        reservations:
          cpus: 0.5
